services:
  flask:
    build: ./flask
    depends_on:
    - mysql
    ports:
    - 80:80
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    ports:
    - 3306:3306
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d/:ro
  vue:
    build: ./vue
    depends_on:
    - mysql
    ports:
    - 8080:8080
    restart: on-failure
version: '3'
