services:
  elasticsearch:
    environment:
    - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
    - 9200:9200
  flask:
    build: ./flask
    depends_on:
    - mysql
    - elasticsearch
    ports:
    - 80:80
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    ports:
    - 3306:3306
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d/:ro
  vue:
    build: ./vue
    depends_on:
    - mysql
    - elasticsearch
    ports:
    - 8080:8080
    restart: on-failure
version: '3'
