MYSQL:
  USERNAME: root
  PASSWORD: root
  DB_NAME: stackbox
  HOST: mysql
  PORT: 3306
  TABLE_NAME: stacks
  COLUMN_NAMES: name,image,build,port

ES:
  INDEX: stacks
  HOST: elasticsearch
  PORT: 9200

KAFKA:
  HOST: kafka
  PORT: 9092
  TOPIC: stackbox

